<?php
declare(strict_types=1);
require __DIR__.'/../vendor/autoload.php';
use Magebean\Engine\{Context, ScanRunner, RequirementCatalog, CheckResult, CheckOutcome, ScanContext, ScanRequest, ScanPlanner, ScanService, ScanReportAssembler, ScanExitPolicy};
use Magebean\Engine\Checks\CheckRegistry;
use Magebean\Console\ScanConsoleRenderer;
use Magebean\Agent\AgentResultMapper;
use Symfony\Component\Console\Output\BufferedOutput;
$n=0;function diagAssert(bool $v,string $m):void{global $n;++$n;if(!$v)throw new RuntimeException($m);}
$root=sys_get_temp_dir().'/mb-diagnostics-'.bin2hex(random_bytes(4));mkdir($root);
try {
 $rules=array_values(array_filter(RequirementCatalog::loadAll()['rules'],static fn(array $r):bool=>empty($r['human_evidence']['required'])));
 $unknown=new CheckRegistry();foreach($rules as$r)foreach($r['checks']as$c)if(!$unknown->has($c['name']))$unknown->register($c['name'],static fn(array$args):CheckResult=>CheckResult::of(CheckOutcome::Unknown,'Fixture collection did not complete'));
 $results=(new ScanRunner(new Context($root,''),['rules'=>$rules],null,$unknown))->run();
 diagAssert(count($results['findings'])===count($rules),'All autonomous inventory members attempted');
 foreach($results['findings']as$f){
  diagAssert($f['status']==='UNKNOWN',$f['id'].' missing evidence cannot PASS/FAIL');
  $g=$f['collection_guidance']??[];diagAssert(trim($g['action']??'')!==''&&trim($g['owner']??'')!==''&&trim($g['category']??'')!=='',$f['id'].' has owner, action and category');
  diagAssert(isset($g['resources'])&&is_array($g['resources']),$f['id'].' structured input resources available');
  diagAssert(($f['evidence']['collection_guidance']??null)===$g,$f['id'].' wire evidence retains guidance');
 }
 $fixture=$rules[0];$fixture['id']='MB-9995';$fixture['review_state']='accepted_scoped_criterion';$fixture['human_evidence']['required']=false;$fixture['obligations']=[['id'=>'O001','role'=>'mandatory','proof'=>'verified_predicate','op'=>'all','checks'=>[['name'=>'fixture_collection','args'=>['file'=>'app/etc/env.php']]]]];$fixture['checks']=$fixture['obligations'][0]['checks'];
 $typed=new CheckRegistry();$typed->register('fixture_collection',static fn(array$args):CheckResult=>CheckResult::of(CheckOutcome::Unknown,'Exact collector failure',['nested'=>['reason_code'=>'FIXTURE_PERMISSION_DENIED','action'=>'Grant read access to the exact fixture input']],null));
 $typedResult=(new ScanRunner(new Context($root,''),['rules'=>[$fixture]],null,$typed))->run();$g=$typedResult['findings'][0]['collection_guidance'];
 diagAssert($g['action']==='Grant read access to the exact fixture input'&&$g['reason_code']==='FIXTURE_PERMISSION_DENIED','Typed collector action/reason precede fallback guesses');diagAssert($g['resources']===['app/etc/env.php'],'Exact declared resource retained');
 $throwing=new CheckRegistry();$calls=0;$throwing->register('fixture_collection',static function(array$args){throw new RuntimeException('password=DO_NOT_LEAK token=DO_NOT_LEAK SQLSTATE details');});$throwing->register('fixture_next',static function(array$args)use(&$calls):CheckResult{++$calls;return CheckResult::of(CheckOutcome::Pass,'Next check completed');});
 $next=$fixture;$next['id']='MB-9996';$next['obligations'][0]['checks']=[['name'=>'fixture_next','args'=>[]]];$next['checks']=$next['obligations'][0]['checks'];
 $thrownResult=(new ScanRunner(new Context($root,''),['rules'=>[$fixture,$next]],null,$throwing))->run();$g=$thrownResult['findings'][0]['collection_guidance'];
 diagAssert($calls===1&&$thrownResult['findings'][1]['status']==='PASS','Internal primary check failure does not abandon later requirement');diagAssert($g['reason_code']==='CHECK_EXECUTION_FAILED'&&$g['owner']==='magebean','Tool defect has correct owner and reason');diagAssert(!str_contains(json_encode($thrownResult),'DO_NOT_LEAK')&&!str_contains(json_encode($thrownResult),'SQLSTATE'),'Raw exception message never emitted');
 $benignCheckpointCalls=0;$checkpointResult=(new ScanRunner(new Context($root,''),['rules'=>[$fixture,$next]],null,$throwing,null,static function()use(&$benignCheckpointCalls){++$benignCheckpointCalls;}))->run();diagAssert($checkpointResult['findings'][0]['status']==='UNKNOWN'&&$checkpointResult['findings'][1]['status']==='PASS'&&$benignCheckpointCalls>0,'Benign worker checkpoint does not make detector exceptions fatal');
 $legacy=['id'=>'LEGACY-FIXTURE','title'=>'Fixture','control'=>'MB-C01','severity'=>'low','checks'=>$fixture['checks']];$propagated=false;try{(new ScanRunner(new Context($root,''),['rules'=>[$legacy]],null,$throwing))->run();}catch(RuntimeException$e){$propagated=str_contains($e->getMessage(),'DO_NOT_LEAK');}diagAssert($propagated,'Legacy check exception propagation preserved');
 $checkpointError=new RuntimeException('worker cancellation');$propagated=false;try{(new ScanRunner(new Context($root,''),['rules'=>[$fixture]],null,$typed,null,static function()use($checkpointError){throw $checkpointError;}))->run();}catch(RuntimeException$e){$propagated=$e===$checkpointError;}diagAssert($propagated,'Worker checkpoint cancellation propagates unchanged');
 $set=new \Magebean\Engine\Collectors\CollectorSet();$swallowing=CheckRegistry::fromContext(new Context($root,''),$set);$swallowing->register('fixture_collection',static function()use($set):CheckResult{try{$set->session->checkpoint();}catch(\Throwable){}return CheckResult::of(CheckOutcome::Pass,'Detector swallowed callback');});$callbackCount=0;$propagated=false;try{(new ScanRunner(new Context($root,''),['rules'=>[$fixture]],null,$swallowing,null,static function()use(&$callbackCount,$checkpointError){if(++$callbackCount===3)throw $checkpointError;}))->run();}catch(RuntimeException$e){$propagated=$e===$checkpointError;}diagAssert($propagated,'Detector cannot swallow a collector worker cancellation and produce a clean result');
 $mapped=(new AgentResultMapper())->map($typedResult,['manifest_hash'=>'fixture'],['MB-9995'=>['assessment_item_id'=>'item-1']],[],$root);diagAssert($mapped['results'][0]['status']==='error','Agent missing evidence stays compatible error');diagAssert($mapped['results'][0]['evidence']['collection_guidance']['action']==='Grant read access to the exact fixture input','Agent preserves structured next action');
 $human=$fixture;$human['human_evidence']=['required'=>true,'instructions'=>'Review the real payment flow and retain runtime evidence.'];$human['obligations'][0]['role']='supporting';$human['obligations'][0]['proof']='heuristic';
 $humanResult=(new ScanRunner(new Context($root,''),['rules'=>[$human]],null,$typed))->run();$hf=$humanResult['findings'][0];diagAssert($hf['status']==='MANUAL_REVIEW','Optional collection gap does not replace a human assessment boundary');diagAssert($hf['detail'][0]['collection_guidance']['action']==='Grant read access to the exact fixture input','Supporting missing observations retain a precise action');diagAssert($hf['evidence']['obligations'][0]['checks'][0]['collection_guidance']['resources']===['app/etc/env.php'],'Supporting check evidence retains resource guidance for agent');
 $humanResult['meta']['rules_filter']=['MB-9995'];$out=new BufferedOutput();(new ScanConsoleRenderer())->renderPrettySummary($out,$humanResult,$root);diagAssert(str_contains($out->fetch(),'Action: Grant read access to the exact fixture input'),'Explicit human detail shows technical collection action');
 $context=new ScanContext($root,'');$real=CheckRegistry::fromContext($context->toLegacy());$plan=(new ScanPlanner())->planCli(new ScanRequest($context,['profile'=>'baseline','rules'=>'MB-0039']),$real);diagAssert($plan!==null,'Selected reviewed DB requirement plans');
 $registry=new CheckRegistry();$registry->register('deployment_indexers_database_ready',static fn(array$args):CheckResult=>CheckResult::of(CheckOutcome::Unknown,'Cannot read indexer_state database'));
 $assembled=(new ScanReportAssembler())->assemble((new ScanService())->run($plan,null,$registry),$plan)->toLegacy();$out=new BufferedOutput();(new ScanConsoleRenderer())->renderPrettySummary($out,$assembled,$root);$text=$out->fetch();diagAssert(str_contains($text,'SELECT')&&str_contains($text,'How to resolve MB-0039'),'Detailed console exposes actionable DB collection guidance');diagAssert(!str_contains($text,'[INCONCLUSIVE]')&&str_contains($text,'[EXECUTION ERROR]'),'Autonomous detailed output consistently distinguishes execution error');diagAssert((new ScanExitPolicy())->code($assembled)===3,'Reviewed autonomous collection failure exits three');
 echo 'AutomationDiagnosticsTest: '.$n.' assertions across '.count($rules)." autonomous requirements passed\n";
}finally{rmdir($root);}
