<?php
declare(strict_types=1);
require __DIR__.'/../vendor/autoload.php';
use Magebean\Engine\{RequirementCatalog,RequirementAssessmentEvaluator,RequirementOutcome,CheckResult,CheckOutcome};
$index=array_column(RequirementCatalog::loadAll()['rules'],null,'id');$source=RequirementCatalog::read('pci-criterion-definitions')['criteria'];$n=0;$assert=static function(bool $ok,string $m)use(&$n):void{++$n;if(!$ok)throw new RuntimeException($m);};$reviewed=0;
foreach($index as$r){if(!$r['human_evidence']['required']||in_array('OWASP-ASVS',array_column($r['alignments'],'standard'),true))continue;++$reviewed;$assert(trim($r['human_evidence']['instructions'])!=='','Concrete human evidence guidance exists '.$r['id']);$r['applicability']['state']='APPLICABLE';foreach([CheckOutcome::Pass,CheckOutcome::Fail,CheckOutcome::Unknown]as$outcome){$result=RequirementAssessmentEvaluator::evaluate($r,fn()=>CheckResult::of($outcome,'Optional observation'));$assert($result->outcome===RequirementOutcome::ManualReview,'Supporting observation does not override human scope '.$r['id'].' '.$outcome->value);}foreach($r['alignments']as$a){$assert(($a['scoped_criterion']??$r['criterion'])===$source[$a['reference']]['criterion'],'Complete persisted source criterion retained '.$r['id'].' '.$a['reference']);$assert(str_contains($r['human_evidence']['instructions'],$r['criterion']),'Human instructions preserve full PCI criterion '.$r['id']);}}
$assert($reviewed===299,'All257PCI+42unaligned desk-reviewed definitions covered');
$roleFix=json_decode(file_get_contents(__DIR__.'/../docs/human-evidence-role-fix-review.json'),true,512,JSON_THROW_ON_ERROR);$roleCount=0;
foreach($roleFix['changes']as$change){$r=$index[$change['id']];$assert($r['human_evidence']['required'],'Role review does not promote human requirement');foreach($change['previous_obligations']as$i=>$old){$new=$r['obligations'][$i];$allowed=$new;if(in_array($old['id'],$change['role_changed_obligation_ids'],true)){$assert($old['role']==='mandatory'&&$old['proof']==='heuristic'&&$new['role']==='supporting','Only specified optional heuristic roles changed');$allowed['role']='mandatory';}$assert($allowed===$old,'Checks arguments operator and proof preserved per explicit reviewed obligation');}if($change['role_changed_obligation_ids']!==[])++$roleCount;}
$assert($roleCount===37,'Exactly37unaligned role fixes');
foreach(['MB-0486'=>'3.3.3','MB-0487'=>'3.4.1','MB-0494'=>'3.6.1.1']as$id=>$ref){$r=$index[$id];$s=$source[$ref];$assert($r['criterion']===$s['criterion'],'Source correction exact '.$id);$assert($r['applicability']['entity_restriction']===$s['entity_restriction']&&$r['applicability']['effective_from']===$s['effective_from'],'Applicability/effective date metadata preserved '.$id);$assert($r['source_metadata']===$s['source_metadata'],'Source metadata exact '.$id);$assert(!str_contains($r['criterion'],'continued on next page')&&!str_contains($r['criterion'],'refer to'),'PDF page/effective-date extraction fragments removed '.$id);$assert($r['human_evidence']['required']&&$r['checks']===[],'Restored normative clause remains human-only '.$id);}
$assert(str_contains($index['MB-0494']['criterion'],'Description of the key usage for each key')&&str_contains($index['MB-0494']['criterion'],'hardware security modules (HSMs)'),'Missing cryptographic architecture clauses restored');
echo "Human PCI/unaligned desk review: $n assertions passed\n";
