<?php
declare(strict_types=1);
require __DIR__.'/../vendor/autoload.php';
use Magebean\Engine\{RequirementCatalog,RequirementProfileCatalog,LegacyRequirementAliases};
function verify(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
$all=RequirementCatalog::loadAll();verify(count($all['rules'])===687,'Full independent inventory count');$ids=array_column($all['rules'],'id');verify(count(array_unique($ids))===687,'Unique identities');verify($all['assessment_model']==='internal-requirement-v1','Catalog model');
foreach($all['rules'] as $r){verify((bool)preg_match('/^MB-\d{4}$/D',$r['id']),'Opaque internal identity');verify(isset($r['criterion'],$r['revision'],$r['obligations'],$r['human_evidence']),'Standalone criterion policy');verify(!isset($r['requirements'],$r['requirement'],$r['legacy_rule_ids']),'No second relationship identity');foreach($r['obligations'] as $o){verify(in_array($o['proof'],['verified_predicate','heuristic','human'],true),'Proof classification');foreach($o['checks'] as $c){verify(!str_starts_with($c['name'],'asvs_')&&!in_array($c['name'],['requirement_assessment','human_manual_review_required','manual_review'],true),'Functions independent of requirements');verify(!isset($c['args']['requirement']),'No requirement dispatcher arguments');}}}
verify(count(RequirementCatalog::forProfile('baseline')['rules'])===684,'Baseline assessment profile retains its full contextual inventory');verify(count(RequirementCatalog::forProfile('asvs-l1', ['graphql','oauth','oidc','saml','websocket','file_upload','api','jwt'])['rules'])===69,'ASVS L1 selection');verify(count(RequirementCatalog::forProfile('pci')['rules'])===257,'PCI independent selection');verify(count(RequirementCatalog::resolveAlias('MB-R001'))===1,'Baseline legacy alias preferred once');verify(RequirementCatalog::resolveAlias($ids[0])===[$ids[0]],'Internal identity resolves itself');verify(RequirementCatalog::resolveAlias('no-such-alias')===[],'Unknown aliases not invented');
$l3=RequirementCatalog::forProfile('asvs-l3');verify($l3['inventory_count']===344,'Authoritative profile inventory remains344');verify(count($l3['rules'])+count($l3['omitted_requirements'])===344,'Every profile member selected or explicitly omitted');foreach($l3['omitted_requirements'] as $o)verify($o['reason_code']==='CAPABILITY_CONTEXT_MISSING','Missing capability explained explicitly');
$tmp=tempnam(sys_get_temp_dir(),'mb-profile-');file_put_contents($tmp,json_encode(['id'=>'custom','requirement_ids'=>[$ids[0]]]));verify(count(RequirementCatalog::forProfile($tmp)['rules'])===1,'Persisted custom primary profile');file_put_contents($tmp,json_encode(['id'=>'custom','requirement_ids'=>['MB-9999']]));try{RequirementCatalog::forProfile($tmp);throw new RuntimeException('Unknown custom requirement accepted');}catch(RuntimeException $e){verify(str_contains($e->getMessage(),'Unknown internal'),'Reject unknown custom IDs');}finally{unlink($tmp);}echo "Internal catalog assertions passed.\n";
