<?php
declare(strict_types=1);
require __DIR__.'/../vendor/autoload.php';
use Magebean\Engine\{RequirementCatalog,RequirementProfileCatalog,ScanContext,ScanRequest,ScanPlanner};
use Magebean\Engine\Checks\CheckRegistry;
use Magebean\Application;
use Symfony\Component\Console\Tester\CommandTester;
function mergedAssert(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
$all=RequirementCatalog::loadAll();mergedAssert(count($all['rules'])===687,'Approved consolidation active count');$refs=['OWASP-ASVS'=>[],'PCI-DSS'=>[]];foreach($all['rules'] as $r)foreach($r['alignments'] as $a)if(isset($refs[$a['standard']])){mergedAssert(!isset($refs[$a['standard']][$a['reference']]),'Standard reference has one surviving owner');$refs[$a['standard']][$a['reference']]=$r['id'];}mergedAssert(count($refs['OWASP-ASVS'])===345&&count($refs['PCI-DSS'])===280,'Consolidation retains all625 normative references');
$known=array_fill_keys(array_column($all['rules'],'id'),true);foreach(RequirementProfileCatalog::all() as $p){mergedAssert(count($p['requirement_ids'])===count(array_unique($p['requirement_ids'])),'Profile canonical membership deduplicated');foreach($p['requirement_ids'] as $id)mergedAssert(isset($known[$id]),'Profile membership is active canonical');}
$merged=array_column($all['rules'],null,'id')['MB-0379'];mergedAssert($merged['revision']>=3&&$merged['human_evidence']['required']&&$merged['review_state']==='security_reviewed'&&count(array_filter($merged['obligations'],static fn(array$o):bool=>$o['proof']==='human'))===1,'Reviewed counterexample retains human evidence for the complete combined criterion');mergedAssert(in_array('MB-C07',$merged['control_tags'],true)&&$merged['control']!=='MB-C07','Merged source control tag retained');$filtered=RequirementCatalog::loadAll(['MB-C07']);mergedAssert(in_array($merged['id'],array_column($filtered['rules'],'id'),true),'Catalog filtering honors secondary control tags');mergedAssert(in_array('MB-C07',$all['controls'],true),'Pack control inventory includes merged tags');
$root=sys_get_temp_dir().'/mb-merged-contract-'.bin2hex(random_bytes(5));mkdir($root);try{$ctx=new ScanContext($root,'');$registry=CheckRegistry::fromContext($ctx->toLegacy());$planner=new ScanPlanner();$profile=$root.'/profile.json';file_put_contents($profile,json_encode(['id'=>'one-merged','requirement_ids'=>[$merged['id']]]));$plan=$planner->planCli(new ScanRequest($ctx,['profile'=>$profile,'controls'=>'MB-C07','include-manual-review'=>true]),$registry);mergedAssert($plan!==null&&array_column($plan->pack['rules'],'id')===[$merged['id']],'Planner honors secondary control selection');$tester=new CommandTester((new Application())->find('rules:list'));$tester->execute(['--profile'=>$profile,'--control'=>'MB-C07','--include-manual-review'=>true,'--no-ansi'=>true]);mergedAssert(str_contains($tester->getDisplay(),$merged['id']),'Listing honors secondary control selection');$config=$root.'/.magebean.json';file_put_contents($config,json_encode(['exclude_controls'=>['MB-C07']]));$plan=$planner->planCli(new ScanRequest($ctx,['rules'=>$merged['id']]),$registry);mergedAssert($plan===null,'Excluding secondary control cannot leave merged criterion selected');unlink($config);unlink($profile);}finally{rmdir($root);}echo "MergedRequirementContractTest passed\n";
