<?php
declare(strict_types=1);
require __DIR__.'/../vendor/autoload.php';
use Magebean\Engine\{ScanContext,ScanRequest,ScanPlanner,RequirementCatalog,ScanService};
use Magebean\Engine\Checks\CheckRegistry;
function primaryAssert(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
$root=sys_get_temp_dir().'/mb-primary-planner-'.bin2hex(random_bytes(5));mkdir($root);
try{
 $ctx=new ScanContext($root,'','',['meta'=>['target_mode'=>'LOCAL']]);$registry=CheckRegistry::fromContext($ctx->toLegacy());$planner=new ScanPlanner();$request=fn(array $o)=>new ScanRequest($ctx,$o);$events=[];$diagnostic=function($d)use(&$events){$events[]=$d->message();};
 $basic=$planner->planCli($request([]),$registry,$diagnostic);primaryAssert($basic!==null,'Default primary plan validates: '.implode(';',$events));primaryAssert(count($basic->pack['rules'])===20,'Default basic criteria');foreach($basic->pack['rules'] as $r)primaryAssert(str_starts_with($r['id'],'MB-'),'Default IDs internal');
 $hybridCtx=new ScanContext($root,'https://fixture.example','',['meta'=>['target_mode'=>'HYBRID']]);$hybrid=$planner->planCli(new ScanRequest($hybridCtx,[]),CheckRegistry::fromContext($hybridCtx->toLegacy()),$diagnostic);primaryAssert($hybrid!==null&&count($hybrid->pack['rules'])===20,'Hybrid target retains local recipes');primaryAssert($hybrid->request->context->get('meta',[])['target_mode']==='HYBRID','Hybrid report metadata preserved');
 $all=RequirementCatalog::loadAll()['rules'];$first=$all[0]['id'];$second=$all[1]['id'];$config=$root.'/.magebean.json';file_put_contents($config,json_encode(['exclude_rules'=>[$first],'override_rules'=>[$second=>['severity'=>'critical']]]));
 $explicit=$planner->planCli($request(['rules'=>$first.','.$second]),$registry,$diagnostic);primaryAssert($explicit!==null&&array_column($explicit->pack['rules'],'id')===[$second],'Explicit selection respects project exclusion');primaryAssert($explicit->pack['rules'][0]['severity']==='critical','Explicit selection respects presentation override');
 file_put_contents($config,json_encode(['override_rules'=>[$second=>['criterion'=>'weakened']]]));$thrown=false;try{$planner->planCli($request(['rules'=>$second]),$registry);}catch(RuntimeException $e){$thrown=str_contains($e->getMessage(),'immutable');}primaryAssert($thrown,'Criterion override rejected');unlink($config);
 $remoteCtx=new ScanContext('URL:https://fixture.example','https://fixture.example','',['meta'=>['target_mode'=>'REMOTE']]);$remoteRegistry=CheckRegistry::fromContext($remoteCtx->toLegacy());$remoteIds=[];foreach($all as $r)if(isset($r['execution_variants']['REMOTE']))$remoteIds[]=$r['id'];primaryAssert(count($remoteIds)===9,'Nine remote baseline variants');
 $defaultRemote=$planner->planCli(new ScanRequest($remoteCtx,['include-manual-review'=>true]),$remoteRegistry,$diagnostic);primaryAssert($defaultRemote!==null&&count($defaultRemote->pack['rules'])===9,'Default remote preserves bounded nine-assessment scope');
 $remote=$planner->planCli(new ScanRequest($remoteCtx,['rules'=>implode(',',$remoteIds)]),$remoteRegistry,$diagnostic);primaryAssert($remote!==null&&count($remote->pack['rules'])===9,'Remote variant plans validate');foreach($remote->pack['rules'] as $r)primaryAssert(($r['execution_scope']??'')==='REMOTE','Target recipe selected without changing criterion identity');
 $manifest=['schema_version'=>'1.0','rules'=>[['rule_key'=>$second,'assessment_item_id'=>'a'],['rule_key'=>'MB-R037','assessment_item_id'=>'b'],['rule_key'=>'MB-9999','assessment_item_id'=>'c']]];$agent=$planner->planAgent($request(['manifest'=>$manifest]));primaryAssert(array_column($agent->pack['rules'],'id')===[$second,'MB-R037'],'Mixed manifest preserves supported order');primaryAssert(count($agent->metadata['manifestIndex'])===3&&count($agent->metadata['unsupported'])===1,'Manifest cardinality exact');
 $manifest['rules'][]=$manifest['rules'][0];$thrown=false;try{$planner->planAgent($request(['manifest'=>$manifest]));}catch(RuntimeException $e){$thrown=str_contains($e->getMessage(),'Duplicate');}primaryAssert($thrown,'Duplicate internal assessment rejected');
 $manifest=['schema_version'=>'1.0','assessment_level'=>4,'rules'=>[['rule_key'=>$second,'assessment_item_id'=>'a']]];$thrown=false;try{$planner->planAgent($request(['manifest'=>$manifest]));}catch(RuntimeException $e){$thrown=true;}primaryAssert($thrown,'Manifest assessment context validated');
 $contextual=null;foreach($all as $r)if(isset($r['applicability']['capability'])){$contextual=$r;break;}primaryAssert($contextual!==null,'Contextual requirement fixture');$manifest=['schema_version'=>'1.0','rules'=>[['rule_key'=>$contextual['id'],'assessment_item_id'=>'a']]];$agent=$planner->planAgent($request(['manifest'=>$manifest]));primaryAssert($agent->pack['rules'][0]['applicability']['state']==='UNKNOWN','Missing context cannot be verified N/A');$manifest['capabilities']=[$contextual['applicability']['capability']];$agent=$planner->planAgent($request(['manifest'=>$manifest]));primaryAssert($agent->pack['rules'][0]['applicability']['state']==='APPLICABLE','Explicit capability recognized');
 $oldProfile=$root.'/old-profile.json';file_put_contents($oldProfile,json_encode(['id'=>'old-custom','title'=>'Legacy profile fixture','rules'=>['MB-R037']]));$old=$planner->planCli($request(['profile'=>$oldProfile]),$registry,$diagnostic);primaryAssert($old!==null&&array_column($old->pack['rules'],'id')===['MB-R037'],'Legacy custom profile routes compatibility');unlink($oldProfile);
 $ruleFile=$root.'/custom-rules.json';file_put_contents($ruleFile,json_encode(['controls'=>['MB-C02'],'rules'=>[['id'=>'CUSTOM-1','control'=>'MB-C02','severity'=>'low','title'=>'Fixture custom check','checks'=>[['name'=>'magento_production_mode','args'=>[]]]]]]));file_put_contents($config,json_encode(['rule_files'=>[$ruleFile],'include_rules'=>['CUSTOM-1']]));$old=$planner->planCli($request(['profile'=>'baseline']),$registry,$diagnostic);primaryAssert($old!==null&&array_column($old->pack['rules'],'id')===['CUSTOM-1'],'Legacy rule_files supported without silent ignore');unlink($config);unlink($ruleFile);
 echo "PrimaryRequirementPlanningTest passed\n";
}finally{foreach(glob($root.'/*')?:[] as $f)unlink($f);foreach(glob($root.'/.*')?:[] as $f)if(is_file($f))unlink($f);rmdir($root);}
