<?php
declare(strict_types=1);
require_once __DIR__ . '/../vendor/autoload.php';
use Magebean\Engine\Pci\PciAssessmentReportBuilder;
use Magebean\Engine\Reporting\{JsonReporter, SarifReporter, HtmlReporter};
use Magebean\Console\ScanConsoleRenderer;
use Symfony\Component\Console\Output\BufferedOutput;
$count = 0;
function expectConsumer(bool $condition, string $message): void { global $count; $count++; if (!$condition) throw new RuntimeException($message); }
$dir = sys_get_temp_dir() . '/magebean-consumer-' . bin2hex(random_bytes(6)); mkdir($dir);
try {
    $finding = ['id'=>'MB-0001','title'=>'Test independent requirement','severity'=>'high','status'=>'UNKNOWN','passed'=>null,'message'=>'','requirement'=>['id'=>'MB-0001','revision'=>1,'criterion'=>'Confirm the obligation.'],'alignment'=>[['standard'=>'PCI-DSS','version'=>'4.0.1','reference'=>'2.2.1','relationship'=>'partial'],['standard'=>'OWASP-ASVS','version'=>'5.0.0','reference'=>'2.2.1','relationship'=>'supporting']], 'coverage'=>'PARTIALLY_AUTOMATED', 'applicability'=>['status'=>'UNKNOWN'], 'profile'=>['mappings'=>[['requirement'=>'9.9.9','coverage'=>'DIRECT']]]];
    $scan = ['summary'=>['total'=>1,'passed'=>0,'failed'=>0,'unknown'=>1,'path'=>$dir], 'meta'=>['profile'=>['id'=>'pci','title'=>'PCI'], 'rules_filter'=>['MB-0001']], 'findings'=>[$finding]];
    $coverage = ['requirements'=>[['id'=>'2.2.1','coverage'=>'PARTIAL'],['id'=>'9.9.9','coverage'=>'UNMAPPED']]];
    $app = ['requirements'=>[['requirement'=>'2.2.1','status'=>'APPLICABLE','rationale'=>'Scoped'],['requirement'=>'9.9.9','status'=>'APPLICABLE','rationale'=>'Scoped']]];
    $builder = new PciAssessmentReportBuilder();
    $report = $builder->build($scan,$coverage,[],$app,[],false);
    expectConsumer(count($report['requirements'][0]['magebean_findings']) === 1, 'Primary alignment must feed PCI report without profile mappings');
    expectConsumer($report['requirements'][1]['magebean_findings'] === [], 'Primary findings cannot fall back to stale profile mappings');
    expectConsumer($report['requirements'][0]['assessment_status'] === 'HUMAN_VERIFICATION_REQUIRED', 'UNKNOWN is not certification or technical failure');
    $scan['findings'][0]['alignment'][] = $finding['alignment'][0];
    $report = $builder->build($scan,$coverage,[],$app,[],false);
    expectConsumer(count($report['requirements'][0]['magebean_findings']) === 1, 'Repeated standard alignment cannot duplicate finding');
    $scan['findings'][0]['alignment'] = [['standard'=>'PCI-DSS','version'=>'3.2.1','id'=>'2.2.1']];
    $report = $builder->build($scan,$coverage,[],$app,[],false);
    expectConsumer($report['requirements'][0]['magebean_findings'] === [], 'Wrong PCI version cannot map by number alone');
    $legacy = $finding; unset($legacy['requirement'], $legacy['alignment']); $legacy['id']='MB-R001';
    $report = $builder->build(['findings'=>[$legacy]],$coverage,[],$app,[],false);
    expectConsumer(count($report['requirements'][1]['magebean_findings']) === 1, 'Historical profile mapping remains supported');
    $shared = $finding; $shared['status'] = 'FAIL';
    $shared['alignment'] = [['standard'=>'PCI-DSS','version'=>'4.0.1','reference'=>'2.2.1'],['standard'=>'PCI-DSS','version'=>'4.0.1','reference'=>'9.9.9']];
    $sharedReport = $builder->build(['findings'=>[$shared]],$coverage,[],$app,[],false);
    foreach ($sharedReport['requirements'] as $sharedRow) {
        expectConsumer($sharedRow['magebean_findings'][0]['status']==='MANUAL_REVIEW' && $sharedRow['magebean_findings'][0]['group_status']==='FAIL' && $sharedRow['assessment_status']==='HUMAN_VERIFICATION_REQUIRED','Compound failure retains canonical signal without asserting each standard scope failed');
    }
    expectConsumer($shared['status']==='FAIL','Scoped projection does not alter canonical scan failure');
    array_pop($shared['alignment']);
    $singleReport = $builder->build(['findings'=>[$shared]],$coverage,[],$app,[],false);
    expectConsumer($singleReport['requirements'][0]['assessment_status']==='TECHNICAL_FINDING','Single aligned criterion retains technical failure');
    $scan['findings'] = [$finding];
    (new JsonReporter())->write($scan,$dir.'/result.json');
    expectConsumer(json_decode(file_get_contents($dir.'/result.json'),true) === $scan,'JSON preserves singular identity and alignment');
    (new SarifReporter())->write($scan,$dir.'/result.sarif');
    $result=json_decode(file_get_contents($dir.'/result.sarif'),true)['runs'][0]['results'][0];
    expectConsumer($result['ruleId']==='MB-0001' && $result['level']==='note','SARIF uses internal identity and inconclusive note');
    expectConsumer($result['properties']['requirement']===$finding['requirement'] && $result['properties']['alignment']===$finding['alignment'],'SARIF preserves requirement metadata');
    (new SarifReporter())->write(['findings'=>[$legacy]],$dir.'/legacy.sarif');
    expectConsumer(json_decode(file_get_contents($dir.'/legacy.sarif'),true)['runs'][0]['results'][0]['properties']===['magebean_status'=>'UNKNOWN'],'SARIF legacy properties retain contract');
    file_put_contents($dir.'/template.html','<html><table><tbody>{{table}}</tbody></table>{{cve_section}}</html>');
    (new HtmlReporter($dir.'/template.html'))->write($scan,$dir.'/result.html');
    $html=file_get_contents($dir.'/result.html');
    expectConsumer(str_contains($html,'Insufficient evidence to determine this requirement.'),'HTML primary UNKNOWN is evidence insufficiency');
    expectConsumer(!str_contains($html,'baseline/MB-REQ') && !str_contains($html,'Some CVE-related rules'),'HTML must not invent documentation URLs or CVE cause');
    $out=new BufferedOutput(); (new ScanConsoleRenderer())->renderPrettySummary($out,$scan,$dir); $text=$out->fetch();
    expectConsumer(str_contains($text,"--profile='pci' --rules=MB-0001"),'Rerun preserves internal requirement profile context');
    expectConsumer(!str_contains($text,'baseline/MB-REQ'),'Console must not invent hosted requirement page');
    $scan['meta']['profile_selector'] = '.magebean/profiles/company.json';
    $scan['meta']['capabilities'] = ['oauth_oidc'=>true,'ldap'=>false];
    $scan['meta']['target_mode'] = 'HYBRID'; $scan['meta']['url'] = 'https://example.test';
    $out = new BufferedOutput(); (new ScanConsoleRenderer())->renderPrettySummary($out,$scan,$dir); $text = $out->fetch();
    expectConsumer(str_contains($text,"--profile='.magebean/profiles/company.json' --capabilities='oauth_oidc' --url='https://example.test' --rules=MB-0001"),'Rerun retains custom profile, enabled capabilities and hybrid URL');

    $command = (new \Magebean\Application())->find('rules:list');
    $tester = new \Symfony\Component\Console\Tester\CommandTester($command);
    $tester->execute(['--profile'=>'baseline','--include-manual-review'=>true,'--no-ansi'=>true]); $text = $tester->getDisplay();
    preg_match_all('/^(MB-\d+) \[/m',$text,$ids);
    $expectedIds = array_column(\Magebean\Engine\RequirementCatalog::forProfile("baseline")['rules'],'id'); $listedIds = $ids[1]; sort($expectedIds); sort($listedIds);
    expectConsumer($listedIds === $expectedIds && count(array_unique($listedIds)) === count($listedIds),'Baseline listing contains each selected persisted identity once, with no retired aliases');
    expectConsumer(preg_match('/\bMB-R\d{3}\b/', $text) !== 1 && !str_contains($text,'OWASP-ASVS:'),'Primary listing excludes compatibility inventory identities');
    $tester->execute(['--profile'=>'basic','--control'=>'MB-C01','--no-ansi'=>true]); $text = $tester->getDisplay();
    preg_match_all('/^MB-\d+ \[([^\]]+)\]/m',$text,$controls);
    expectConsumer($controls[1] !== [] && count(array_unique($controls[1])) === 1 && $controls[1][0] === 'MB-C01','Control filters primary requirements after profile selection');
    $tester->execute(['--profile'=>'pci','--include-manual-review'=>true,'--no-ansi'=>true]);
    $pciActiveCount = count(\Magebean\Engine\RequirementCatalog::forProfile('pci')['rules']);
    expectConsumer(str_contains($tester->getDisplay(),'Total Rules Listed: ' . $pciActiveCount),'PCI listing reports active internal requirements rather than duplicated standard references');
    $metadata = ['configBasePath'=>$dir,'configFile'=>'','activeProfile'=>['id'=>'pci'],'standard'=>'PCI-DSS','isPciProfile'=>false,'profileRulesTotal'=>1,'profileManualRulesTotal'=>0,'manualRulesExcluded'=>0,'includeManualReview'=>false,'hasExplicitRuleSelection'=>true,'requestedIds'=>['MB-0001'],'controlsFilter'=>[], 'capabilities'=>['oauth_oidc'=>true], 'profileSelector'=>'.magebean/profiles/company.json'];
    $request = new \Magebean\Engine\ScanRequest(new \Magebean\Engine\ScanContext($dir,'https://example.test','',['meta'=>['target_mode'=>'HYBRID']]));
    $typed = \Magebean\Engine\ScanReport::fromLegacy($scan);
    $assembler = new \Magebean\Engine\ScanReportAssembler();
    $assembled = $assembler->assemble($typed, new \Magebean\Engine\ScanPlan($request,['assessment_model'=>'internal-requirement-v1','rules'=>[]],$metadata))->toLegacy();
    expectConsumer($assembled['meta']['capabilities']===['oauth_oidc'=>true] && $assembled['meta']['profile_selector']==='.magebean/profiles/company.json' && $assembled['meta']['url']==='https://example.test' && $assembled['meta']['assessment_model']==='internal-requirement-v1','Primary assembler records complete rerun context');
    $historical = \Magebean\Engine\ScanReport::fromLegacy(['summary'=>[],'findings'=>[],'meta'=>[]]);
    $assembled = $assembler->assemble($historical, new \Magebean\Engine\ScanPlan($request,['rules'=>[]],$metadata))->toLegacy();
    expectConsumer(!isset($assembled['meta']['assessment_model']) && !isset($assembled['meta']['profile_selector']) && !isset($assembled['meta']['capabilities']) && !isset($assembled['meta']['url']),'Historical assembler does not acquire new primary fields');
    $actualDefinitions = \Magebean\Engine\RequirementCatalog::forProfile('pci')['rules'];
    $actual = array_values(array_filter($actualDefinitions, static fn(array $definition): bool => count(array_filter($definition['alignments'], static fn(array $alignment): bool => $alignment['standard']==='PCI-DSS' && $alignment['reference']==='2.2.2')) > 0))[0];
    $actualScan = (new \Magebean\Engine\ScanRunner(new \Magebean\Engine\Context($dir,''), ['assessment_model'=>'internal-requirement-v1','rules'=>[$actual]]))->run();
    expectConsumer($actualScan['findings'][0]['alignment']===$actual['alignments'] && $actualScan['findings'][0]['requirement']['id']===$actual['id'],'Persisted catalog alignment survives actual runner into finding');
    $actualReport = $builder->build($actualScan,['requirements'=>[['id'=>'2.2.2','coverage'=>'PARTIAL']]],[],['requirements'=>[['requirement'=>'2.2.2','status'=>'APPLICABLE','rationale'=>'Fixture scope']]],[],false);
    expectConsumer(count($actualReport['requirements'][0]['magebean_findings'])===1 && $actualReport['requirements'][0]['magebean_findings'][0]['rule']===$actual['id'],'Real primary PCI finding maps by persisted reference schema');
    expectConsumer($actualReport['requirements'][0]['magebean_findings'][0]['coverage']==='PARTIAL','PCI relationship remains partial evidence, without fabricated direct coverage');
    $pciContext = ['schema_version'=>1,'entity_type'=>'merchant_and_service_provider','issuer_or_issuing_services'=>true,'scope_confirmed'=>true,'payment_architecture'=>'mixed','pan_handling'=>'store','overlays'=>['A1','A2','A3'],'requirement_overrides'=>[]];
    file_put_contents($dir.'/pci-context.json',json_encode($pciContext));
    $request = new \Magebean\Engine\ScanRequest(new \Magebean\Engine\ScanContext($dir,''), ['profile'=>'pci','rules'=>$actual['id'],'include-manual-review'=>true,'pci-context'=>$dir.'/pci-context.json']);
    $registry = \Magebean\Engine\Checks\CheckRegistry::fromContext(new \Magebean\Engine\Context($dir,''));
    $plan = (new \Magebean\Engine\ScanPlanner())->planCli($request,$registry);
    expectConsumer($plan !== null && $plan->pack['assessment_model']==='internal-requirement-v1','Real planner resolves PCI internal selector through primary catalog');
    $serviceReport = (new \Magebean\Engine\ScanService())->run($plan,null,$registry);
    $workflow = $assembler->assemble($serviceReport,$plan)->toLegacy();
    $pciRows = array_column($workflow['pci']['requirements'],null,'requirement');
    $pciActions = array_column($workflow['pci']['human_actions'],null,'requirement');
    expectConsumer(count($pciRows)===280 && count($pciActions)===280,'One primary finding still produces all280 criterion-specific human assessment scopes');
    expectConsumer($pciActions['1.1.1']['scope']!==$pciActions['1.1.2']['scope'] && str_contains($pciActions['1.1.1']['criterion'],'current') && str_contains($pciActions['1.1.2']['criterion'],'roles and responsibilities'),'Human scopes use distinct atomic obligations rather than shared objective-group text');
    expectConsumer($pciRows['12.3.1']['source_metadata']['normative_pdf_pages']===[300] && str_contains($pciRows['12.3.1']['criterion'],'targeted risk analysis'),'PCI source authority retains correct normative page instead of registry cross-reference page254');
    expectConsumer($pciRows['2.2.2']['magebean_findings'][0]['rule']===$actual['id'] && $pciRows['2.2.2']['internal_requirement_id']===$actual['id'],'Primary report alignment and human scope own the same internal requirement');
    expectConsumer($pciRows['1.1.1']['internal_requirement_id']!==$pciRows['1.1.2']['internal_requirement_id'] && $pciActions['1.1.1']['testing_methods']===['examine','interview'],'Unexecuted criteria retain independent identity and authoritative testing methods');
    expectConsumer($pciRows['1.1.1']['internal_requirement_id']===$pciRows['2.1.1']['internal_requirement_id'] && $pciRows['1.1.2']['internal_requirement_id']===$pciRows['2.1.2']['internal_requirement_id'],'Governance scope-union yields one internal identity for repeated predicate scopes');
    expectConsumer($pciRows['1.1.1']['criterion']!==$pciRows['2.1.1']['criterion'] && str_contains($pciRows['1.1.1']['criterion'],'Requirement 1 ') && str_contains($pciRows['2.1.1']['criterion'],'Requirement 2 '),'PCI alignment views preserve original policy domain scope after internal consolidation');
    expectConsumer($pciRows['1.1.1']['source_metadata']['normative_pdf_pages']===[44] && $pciRows['2.1.1']['source_metadata']['normative_pdf_pages']===[66],'Consolidation retains per-reference normative provenance rather than shared canonical source page');
    expectConsumer($pciRows['3.3.1']['internal_requirement_id']===$pciRows['3.3.1.1']['internal_requirement_id'] && $pciRows['3.3.1']['internal_requirement_id']===$pciRows['3.3.1.2']['internal_requirement_id'] && $pciRows['3.3.1']['internal_requirement_id']===$pciRows['3.3.1.3']['internal_requirement_id'],'SAD parent and subtype report references share one internal nonretention requirement');
    expectConsumer(str_contains($pciRows['3.3.1.2']['criterion'],'card verification code') && str_contains($pciRows['3.3.1.3']['criterion'],'PIN') && $pciRows['3.3.1.2']['criterion']!==$pciRows['3.3.1.3']['criterion'],'SAD alignment views retain exact subtype clause rather than propagating canonical scope to every standard reference');
    expectConsumer($workflow['pci']['summary']['standard_references']===280 && $workflow['pci']['summary']['inventory_requirements']===$pciActiveCount && $workflow['pci']['summary']['evaluated_requirements']===1,'PCI summary distinguishes standard references, active inventory and selected evaluations');
    echo "RequirementConsumerContractTest: PASS ({$count} assertions)\n";
} finally { foreach(glob($dir.'/*') as $file) unlink($file); rmdir($dir); }
