<?php
declare(strict_types=1);
require __DIR__.'/../vendor/autoload.php';
use Magebean\Engine\{RequirementCatalog,ScanPlanner,ScanContext,ScanRequest};
use Magebean\Engine\Checks\CheckRegistry;
use Magebean\Agent\AgentResultMapper;
function redirectAssert(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);}
$old='MB-0068';$canonical=RequirementCatalog::resolveAlias($old);redirectAssert(count($canonical)===1&&$canonical[0]!==$old,'Retired criterion resolves to active identity');$id=$canonical[0];$dir=sys_get_temp_dir().'/mb-redirect-'.bin2hex(random_bytes(5));mkdir($dir);
try{
 $ctx=new ScanContext($dir,'');$planner=new ScanPlanner();$registry=CheckRegistry::fromContext($ctx->toLegacy());$cli=$planner->planCli(new ScanRequest($ctx,['rules'=>$old.','.$id]),$registry);redirectAssert($cli!==null&&array_column($cli->pack['rules'],'id')===[$id],'Retired and live CLI selectors execute once');
 $manifest=['schema_version'=>'1.0','manifest_hash'=>'hash','rules'=>[['rule_key'=>$old,'assessment_item_id'=>'retired-item'],['rule_key'=>$id,'assessment_item_id'=>'current-item'],['rule_key'=>'MB-9999','assessment_item_id'=>'unknown-item']]];$plan=$planner->planAgent(new ScanRequest($ctx,['manifest'=>$manifest]));redirectAssert(array_column($plan->pack['rules'],'id')===[$id],'Manifest execution deduplicates canonical identity');redirectAssert(count($plan->metadata['manifestBindings'])===2&&count($plan->metadata['unsupported'])===1,'Each requested assessment has binding or unsupported result');
 $scan=['summary'=>['total'=>1,'passed'=>1,'failed'=>0],'findings'=>[['id'=>$id,'status'=>'PASS','message'=>'Confirmed fixture observation','detail'=>[],'evidence'=>['requirement_id'=>$id,'password'=>'secret']]]];$payload=(new AgentResultMapper())->map($scan,$manifest,$plan->metadata['manifestIndex'],$plan->metadata['unsupported'],$dir,$plan->metadata['manifestBindings']);redirectAssert(count($payload['results'])===3,'Payload cardinality follows manifest not execution');redirectAssert(array_column($payload['results'],'rule_key')===[$old,$id,'MB-9999'],'Requested rule keys remain exact');redirectAssert(array_column($payload['results'],'assessment_item_id')===['retired-item','current-item','unknown-item'],'Requested assessment items remain distinct');redirectAssert($payload['summary']['total']===1,'Summary counts unique canonical assessments');redirectAssert($payload['results'][0]['evidence']['requirement_id']===$id,'Evidence retains actual canonical identity');redirectAssert($payload['results'][0]['evidence']['password']==='[REDACTED]','Fanout preserves evidence redaction');redirectAssert(array_keys($payload)===['schema_version','manifest_hash','summary','results'],'Transport envelope unchanged');
 $manifest['rules'][]=$manifest['rules'][0];$thrown=false;try{$planner->planAgent(new ScanRequest($ctx,['manifest'=>$manifest]));}catch(RuntimeException $e){$thrown=str_contains($e->getMessage(),'Duplicate');}redirectAssert($thrown,'Exact internal requested key duplicates remain rejected');
 $config=$dir.'/.magebean.json';file_put_contents($config,json_encode(['exclude_rules'=>[$old]]));$excluded=$planner->planCli(new ScanRequest($ctx,['rules'=>$id]),$registry);redirectAssert($excluded===null,'Retired policy alias excludes canonical requirement');unlink($config);
 $custom=$dir.'/profile.json';file_put_contents($custom,json_encode(['id'=>'redirect-profile','requirement_ids'=>[$old,$id]]));$profile=RequirementCatalog::forProfile($custom);redirectAssert(array_column($profile['rules'],'id')===[$id],'Custom profile resolves retired IDs and deduplicates canonical membership');file_put_contents($config,json_encode(['override_rules'=>[$old=>['severity'=>'critical']]]));$customPlan=$planner->planCli(new ScanRequest($ctx,['profile'=>$custom]),$registry);redirectAssert($customPlan!==null&&$customPlan->pack['rules'][0]['severity']==='critical','Retired override resolves in custom profile without looking up its local display ID');unlink($config);unlink($custom);
 echo "RequirementRedirectTest passed\n";
}finally{foreach(glob($dir.'/.*')?:[] as $f)if(is_file($f))unlink($f);rmdir($dir);}
