<?php
declare(strict_types=1);
namespace Magebean\Console;
use Symfony\Component\Console\Input\{InputInterface,InputOption};use Symfony\Component\Console\Output\OutputInterface;
final class AgentCronCommand extends AgentCommand
{
 protected function configure():void{$this->setName('agent:cron')->setDescription('Print or install the current-user agent cron entry');$this->configureAgentOptions();$this->addOption('install',null,InputOption::VALUE_NONE,'Install without duplicating the entry');}
 protected function execute(InputInterface $input,OutputInterface $output):int{$bin=realpath($_SERVER['argv'][0]??'')?:($_SERVER['argv'][0]??'magebean');$dir=$this->repository($input)->paths->root;$line='* * * * * flock -n '.escapeshellarg($dir.'/cron.lock').' '.escapeshellarg(PHP_BINARY).' '.escapeshellarg($bin).' agent:tick --quiet --config-dir='.escapeshellarg($dir);if(!$input->getOption('install')){$output->writeln($line);return self::SUCCESS;}if(!$input->isInteractive()){$output->writeln('<error>Installing cron requires interactive confirmation.</error>');return self::FAILURE;}$confirm=new \Symfony\Component\Console\Question\ConfirmationQuestion('Install this cron entry for the current user? [y/N] ',false);if(!$this->getHelper('question')->ask($input,$output,$confirm)){$output->writeln('Cron installation cancelled.');return self::SUCCESS;}if(!function_exists('proc_open')){$output->writeln('<error>proc_open is required to install cron.</error>');return self::FAILURE;}$current=(string)shell_exec('crontab -l 2>/dev/null');if(str_contains($current,' agent:tick ')){$output->writeln('Agent cron entry already exists.');return self::SUCCESS;}$tmp=tempnam(sys_get_temp_dir(),'magebean-cron-');file_put_contents($tmp,rtrim($current)."\n".$line."\n");exec('crontab '.escapeshellarg($tmp),$unused,$code);unlink($tmp);if($code!==0){$output->writeln('<error>Unable to install cron entry.</error>');return self::FAILURE;}$output->writeln('<info>Agent cron entry installed for the current user.</info>');return self::SUCCESS;}
}
